import type { NextPage } from 'next'
import WithNaviTabs from "../components/frames/navi_tab";
import Head from "next/head";

// import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
      <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <WithNaviTabs>
          Welcome to Twilio Test App
        </WithNaviTabs>
      </main>
      </>
  )
}

export default Home
